---
- name: Установка NGINX Ingress Controller
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.0/deploy/static/provider/cloud/deploy.yaml
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
