apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-auth
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: {{ .Values.image.repository }}/auth-service:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.services.auth.port }}
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.dbname }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.password }}
        - name: POSTGRES_HOST
          value: {{ .Release.Name }}-postgres
        - name: SECRET_KEY
          value: "your_secret_key_here"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: {{ .Values.services.auth.port }}
      targetPort: {{ .Values.services.auth.port }}
