replicaCount: 1

image:
  repository: your_dockerhub_username
  tag: "latest"
  pullPolicy: Always

postgres:
  enabled: true
  image: postgres:13
  dbname: project_management
  username: admin
  password: password

services:
  auth:
    port: 5000
  user:
    port: 5001
  project:
    port: 5002
  task:
    port: 5003
  report:
    port: 5004
  frontend:
    port: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
